/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Properties;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author adittachakraborty
 */
public final class SignInSignOut extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    String filename = null;
    BufferedImage image2 = null;
    File f = null;
    File filePath = new File(System.getProperty("user.home") + "/Desktop/Login Data.txt");

    /**
     * Creates new form SignInSignOut
     */
    public SignInSignOut() {
        initComponents();
        JFrameIcon();
    }

    //Setting an Icon for jFrame
    private void JFrameIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/icons8-book_shelf.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        regUsername = new javax.swing.JTextField();
        regEmailAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regConfirmPassword = new javax.swing.JPasswordField();
        regPassword = new javax.swing.JPasswordField();
        regPhoneNumber = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        securityQuestion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        regSecurityAnswer = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uniqueUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        RememberMe = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        btnForgottenPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login & Registration");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setText("Username");

        regUsername.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N

        regEmailAddress.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setText("Email Address");

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel9.setText("Confirm Password");

        regConfirmPassword.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N

        regPassword.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N

        regPhoneNumber.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        regPhoneNumber.setActionCommand("<Not Set>");
        regPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regPhoneNumberKeyTyped(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSignUp.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel10.setText("Security Question");

        securityQuestion.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        securityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your favourite color?", "What's your childhood nickname?" }));

        jLabel11.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel11.setText("Security Answer");

        regSecurityAnswer.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        regSecurityAnswer.setActionCommand("<Not Set>");
        regSecurityAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regSecurityAnswerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnReset)
                .addGap(61, 61, 61)
                .addComponent(btnSignUp)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regUsername)
                            .addComponent(regEmailAddress)
                            .addComponent(regPhoneNumber)
                            .addComponent(regPassword)
                            .addComponent(regConfirmPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(securityQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regSecurityAnswer))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(regUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(regEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(regPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(regPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(regConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(regSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSignUp))
                .addGap(25, 25, 25))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel1.setText("Username Or Email Address");

        uniqueUsername.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        uniqueUsername.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        password.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        RememberMe.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        RememberMe.setText("Remember Me (Email Login Only)");

        btnLogin.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnForgottenPassword.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        btnForgottenPassword.setText("Forgotten Password");
        btnForgottenPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgottenPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RememberMe)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox1)
                                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(uniqueUsername)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnLogin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnForgottenPassword)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(uniqueUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jCheckBox1)
                .addGap(25, 25, 25)
                .addComponent(RememberMe)
                .addGap(25, 25, 25)
                .addComponent(btnLogin)
                .addGap(25, 25, 25)
                .addComponent(btnForgottenPassword)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regPhoneNumberKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_regPhoneNumberKeyTyped

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        regUsername.setText(null);
        regEmailAddress.setText(null);
        regPhoneNumber.setText(null);
        regPassword.setText(null);
        regConfirmPassword.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        if (regUsername.getText().equals("") || regEmailAddress.getText().equals("") || regPassword.getPassword().equals("") || regConfirmPassword.getPassword().equals("") || regPhoneNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else {
            try {
                DBclass.createCon();
                String query2 = "SELECT * FROM Registration WHERE Email = '" + regEmailAddress + "'";
                DBclass.pst=DBclass.con.prepareStatement(query2);
                DBclass.rs=DBclass.pst.executeQuery();
                if (DBclass.rs.next()) {
                    JOptionPane.showMessageDialog(this, "Email Already Exists\nEnter Unique Email Address", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    String query = "INSERT INTO Registration (username, email, password, phoneNumber, SecurityQuestion, SecurityAnswer) values (?,?,?,?,?,?)";
                    DBclass.pst = DBclass.con.prepareStatement(query);
                    if (Pattern.matches("^[a-zA-Z]+$", regUsername.getText())) {
                        //Aditta
                        DBclass.pst.setString(1, regUsername.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[ ]{1}+[a-zA-Z]+$", regUsername.getText())) {
                        //Aditta Chakraborty
                        DBclass.pst.setString(1, regUsername.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[ ]+[a-zA-Z]+[ ]{1}+[a-zA-Z]+$", regUsername.getText())) {
                        //AC Aditta Chakraborty
                        DBclass.pst.setString(1, regUsername.getText());
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Name", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                    if (Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z]+[.]{1}+[A-Za-z]+$", regEmailAddress.getText())) {
                        //aditta87@gmail.com
                        DBclass.pst.setString(2, regEmailAddress.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[@]{1}+[a-zA-Z]+[.]{1}+[a-zA-Z]+$", regEmailAddress.getText())) {
                        //aditta@gmail.com
                        DBclass.pst.setString(2, regEmailAddress.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[.]{1}+[a-zA-Z]+[@]{1}+[a-zA-Z]+[.]+[a-zA-Z]+$", regEmailAddress.getText())) {
                        //aditta.test@gmail.com
                        DBclass.pst.setString(2, regEmailAddress.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[.]{1}+[a-zA-Z0-9]+[@]{1}+[a-zA-Z]+[.]+[a-zA-Z]+$", regEmailAddress.getText())) {
                        //aditta.test89@gmail.com
                        DBclass.pst.setString(2, regEmailAddress.getText());
                    } else if (Pattern.matches("^[a-zA-Z]+[.]{1}+[a-zA-Z]+[.]{1}+[0-9]+[@]{1}+[a-zA-Z]+[.]+[a-zA-Z]+$", regEmailAddress.getText())) {
                        //aditta.test.89@gmail.com
                        DBclass.pst.setString(2, regEmailAddress.getText());
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Email", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    
                    if (Arrays.equals(regPassword.getPassword(), regConfirmPassword.getPassword())) {
                        DBclass.pst.setString(3, new String(regPassword.getPassword()));
                    } else {
                        JOptionPane.showMessageDialog(this, "Password Didn't Matched", "", JOptionPane.ERROR_MESSAGE);
                    }
                    
                    DBclass.pst.setString(4, regPhoneNumber.getText());
                    
                    DBclass.pst.setString(5, securityQuestion.getSelectedItem().toString());
                    
                    DBclass.pst.setString(6, regSecurityAnswer.getText());
                    
                    DBclass.pst.executeUpdate();
                    
                    uniqueUsername.setText(regEmailAddress.getText());
                    password.setText(regPassword.getText());
                    JOptionPane.showMessageDialog(this, "Successfully Registered\nNow You May Login");
                }
            } catch (SQLException ex) {
                Logger.getLogger(SignInSignOut.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (uniqueUsername.getText().equals("") || password.getPassword().equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else {
            try {
                DBclass.createCon();
                String query = "SELECT * FROM Registration WHERE Username=? and Password = ?";
                DBclass.pst = DBclass.con.prepareStatement(query);
                DBclass.pst.setString(1, uniqueUsername.getText());
                DBclass.pst.setString(2, new String(password.getPassword()));
                DBclass.rs = DBclass.pst.executeQuery();
                boolean flag = false;
                if (DBclass.rs.next()) {
                    //Getting user ID
                    String id = "SELECT Id FROM Registration WHERE Username = '" + uniqueUsername.getText() + "' and password = '" + this.password.getText() + "'";
                    DBclass.pst = DBclass.con.prepareStatement(id);
                    DBclass.rs = DBclass.pst.executeQuery();
                    if (DBclass.rs.next()) {
                        JOptionPane.showMessageDialog(this, "Hi " + uniqueUsername.getText() + " you are logined as ");
                        Dashboard d = new Dashboard();
                        flag = true;
                        d.setVisible(true);
                        this.setVisible(false);
                    }
                } else {
                    try {
                        DBclass.createCon();
                        String query2 = "SELECT * FROM Registration WHERE Email = ? AND Password = ?";
                        DBclass.pst = DBclass.con.prepareStatement(query2);
                        
                        DBclass.pst.setString(1, uniqueUsername.getText());
                        DBclass.pst.setString(2, new String(password.getPassword()));
                        
                        DBclass.rs = DBclass.pst.executeQuery();
                        if (DBclass.rs.next()) {
                            if (RememberMe.isSelected()) {
                                try {
                                    File ob = new File("LoginData/" + uniqueUsername.getText() + ".txt");
                                    PrintStream data;
                                    data = new PrintStream(ob);
                                    data.println(this.password.getText());
                                } catch (FileNotFoundException ex) {
                                    return;
                                }
                            }
                            
                            //Getting user ID
                            String id = "SELECT Id, Username FROM Registration WHERE Email = '" + uniqueUsername.getText() + "' and password = '" + this.password.getText() + "'";
                            DBclass.pst = DBclass.con.prepareStatement(id);
                            DBclass.rs = DBclass.pst.executeQuery();
                            if (DBclass.rs.next()) {
                                String name = DBclass.rs.getString("Username");
                                JOptionPane.showMessageDialog(this, "Hi " + name + " you are logined as ");
                                Dashboard d = new Dashboard();
                                flag = true;
                                d.setVisible(true);
                                this.setVisible(false);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid Login", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (HeadlessException e) {
                        JOptionPane.showMessageDialog(this, "Email Login Error", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(SignInSignOut.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnForgottenPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgottenPasswordActionPerformed
        ForgottenPassword FP = new ForgottenPassword();
        FP.setVisible(true);
    }//GEN-LAST:event_btnForgottenPasswordActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        File ob = new File("LoginData/" + uniqueUsername.getText() + ".txt");
        try {
            Scanner search = new Scanner(ob);
            while (search.hasNext()) {
                password.setText(search.nextLine());
                //passFound.setText("Password found and pasted");
                //passFound.setForeground(Color.GREEN);
            }
        } catch (FileNotFoundException ex) {
            return;
        }
    }//GEN-LAST:event_passwordFocusGained

    private void regSecurityAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regSecurityAnswerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_regSecurityAnswerKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInSignOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        try {
            Properties props = new Properties();
            props.put("logoString", "AEC");
            BernsteinLookAndFeel.setCurrentTheme(props);
            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignInSignOut().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox RememberMe;
    private javax.swing.JButton btnForgottenPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField regConfirmPassword;
    private javax.swing.JTextField regEmailAddress;
    private javax.swing.JPasswordField regPassword;
    private javax.swing.JTextField regPhoneNumber;
    private javax.swing.JTextField regSecurityAnswer;
    private javax.swing.JTextField regUsername;
    private javax.swing.JComboBox<String> securityQuestion;
    private javax.swing.JTextField uniqueUsername;
    // End of variables declaration//GEN-END:variables
}
