/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storeaccountpassword;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author adittachakraborty
 */
public final class Dashboard extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    static int userId;

    /**
     * Creates new form Dashboard
     *
     * @param userId
     */
    public Dashboard(int userId) {
        initComponents();
        Dashboard.userId = userId;
        AccountTableFetch();
        JFrameIcon();
        adminChecker();
    }

    //Setting an Icon for jFrame
    private void JFrameIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/password.png")));
    }
   
    void adminChecker() {
        try {
            DbClass.createCon();
            String query = "SELECT username FROM Registration where Id = " + userId;
            DbClass.pst = DbClass.con.prepareStatement(query);
            DbClass.rs = DbClass.pst.executeQuery();
            while (DbClass.rs.next()) {
                String uname = DbClass.rs.getString(1);
                if (uname.equals("admin")) {
                    btnDeleteMember.setVisible(true);
                } else if (!uname.equals("admin")) {
                    btnDeleteMember.setVisible(false);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Admin Not Found");
        }
    }

    //For Search button (Searching by Date)
    public void Searchfetch(String websiteName) {
        String search = websiteName;
        try {
            DbClass.createCon();
            String query = "SELECT websitename as 'Website Name', username as 'Username', email as 'Email', password as 'Password', url as 'URL', description as 'Description' FROM StoreAccountPassword where websitename = '" + search + "' and registration_Id = " + userId;
            DbClass.pst = DbClass.con.prepareStatement(query);
            DbClass.rs = DbClass.pst.executeQuery();
            AccountTable.setModel(DbUtils.resultSetToTableModel(DbClass.rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error In Search Fetch", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void AccountTableFetch() {
        try {
            DbClass.createCon();
            String query = "SELECT websitename as 'Website Name', username as 'Username', email as 'Email', password as 'Password', url as 'URL', description as 'Description' FROM StoreAccountPassword where Registration_Id = " + userId;
            DbClass.pst = DbClass.con.prepareStatement(query);
            DbClass.rs = DbClass.pst.executeQuery();

            AccountTable.setModel(DbUtils.resultSetToTableModel(DbClass.rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error In Notes Table Fetch", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AccountTable = new javax.swing.JTable();
        btnAddAccount = new javax.swing.JButton();
        btnUpdateAccount = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnSendBugsReport = new javax.swing.JButton();
        btnUpdateProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtWebsiteName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store Account Password");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        AccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Website Name", "Username", "Email", "Password", "URL", "Description"
            }
        ));
        AccountTable.getTableHeader().setReorderingAllowed(false);
        AccountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AccountTable);

        btnAddAccount.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnAddAccount.setText("Add Account");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnUpdateAccount.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnUpdateAccount.setText("Update Account");
        btnUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnAbout.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnSendBugsReport.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnSendBugsReport.setText("Send Bugs Report");
        btnSendBugsReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBugsReportActionPerformed(evt);
            }
        });

        btnUpdateProfile.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel1.setText("Website Name");

        txtWebsiteName.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel2.setText("Username");

        txtUsername.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel3.setText("Email");

        txtEmail.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel4.setText("Password");

        txtPassword.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel5.setText("URL");

        txtURL.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        jLabel6.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        jLabel7.setText("Copyright © Aditta's Education Centre 2019");

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel8.setText("Search By Website Name");

        txtSearch.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        jLabel9.setText("Version 1.O");

        btnLogOut.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnDeleteMember.setFont(new java.awt.Font("Monaco", 0, 16)); // NOI18N
        btnDeleteMember.setText("Delete Member");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWebsiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddAccount)
                                .addGap(15, 15, 15)
                                .addComponent(btnUpdateAccount)
                                .addGap(15, 15, 15)
                                .addComponent(btnDelete)
                                .addGap(15, 15, 15)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnLogOut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProfile)
                                .addGap(15, 15, 15)
                                .addComponent(btnUpdateProfile)
                                .addGap(15, 15, 15)
                                .addComponent(btnSendBugsReport)
                                .addGap(15, 15, 15)
                                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteMember)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(979, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(22, 22, 22)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWebsiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddAccount)
                            .addComponent(btnUpdateAccount)
                            .addComponent(btnDelete)
                            .addComponent(btnReset)
                            .addComponent(btnLogOut))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProfile)
                            .addComponent(btnUpdateProfile)
                            .addComponent(btnSendBugsReport)
                            .addComponent(btnAbout)
                            .addComponent(btnDeleteMember))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(720, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnSendBugsReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBugsReportActionPerformed
        new ReportToEmail().setVisible(true);
    }//GEN-LAST:event_btnSendBugsReportActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        new Profile(userId).setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        new UpdateProfile(userId).setVisible(true);
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        if (txtWebsiteName.getText().equals("") || txtUsername.getText().equals("") || txtEmail.getText().equals("") || txtPassword.getText().equals("") || txtURL.getText().equals("") || txtDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All fields are required");
        } else {
            try {
                DbClass.createCon();
                String query = "insert into StoreAccountPassword (Registration_Id, WebsiteName, Username, Email, Password, URL, Description) values(?,?,?,?,?,?,?)";
                DbClass.pst = DbClass.con.prepareStatement(query);

                DbClass.pst.setInt(1, userId);
                DbClass.pst.setString(2, txtWebsiteName.getText());
                DbClass.pst.setString(3, txtUsername.getText());
                DbClass.pst.setString(4, txtEmail.getText());
                DbClass.pst.setString(5, txtPassword.getText());
                DbClass.pst.setString(6, txtURL.getText());
                DbClass.pst.setString(7, txtDescription.getText());

                DbClass.pst.executeUpdate();
                AccountTableFetch();
                JOptionPane.showMessageDialog(this, "Account Added Successfully", "Status", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Account Didn't Added", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void AccountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountTableMouseClicked
        //get values from jTable to components by mouse clicked
        int i = AccountTable.getSelectedRow();
        txtWebsiteName.setText(AccountTable.getValueAt(i, 0).toString());
        txtUsername.setText(AccountTable.getValueAt(i, 1).toString());
        txtEmail.setText(AccountTable.getValueAt(i, 2).toString());
        txtPassword.setText(AccountTable.getValueAt(i, 3).toString());
        txtURL.setText(AccountTable.getValueAt(i, 4).toString());
        txtDescription.setText(AccountTable.getValueAt(i, 5).toString());
    }//GEN-LAST:event_AccountTableMouseClicked
    int id = 0;
    private void btnUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountActionPerformed
        try {
            DbClass.createCon();
            String query = "select Id from StoreAccountPassword where Registration_Id = " + Dashboard.userId + " and websitename = '" + txtWebsiteName.getText() + "' and username = '" + txtUsername.getText() + "' and url = '" + txtURL.getText() + "'";
            System.out.println(query);
            DbClass.pst = DbClass.con.prepareStatement(query);
            DbClass.rs = DbClass.pst.executeQuery();
            if (DbClass.rs.next()) {
                id = DbClass.rs.getInt(1);
                System.out.println("id : " + DbClass.rs.getInt(1));
                try {
                    String query1 = "update StoreAccountPassword set WebsiteName = ?, Username = ?, Email = ?, Password = ?, URL = ?, Description = ? where id = " + id + " and Registration_Id = " + userId;
                    DbClass.pst = DbClass.con.prepareStatement(query1);

                    DbClass.pst.setString(1, txtWebsiteName.getText());
                    DbClass.pst.setString(2, txtUsername.getText());
                    DbClass.pst.setString(3, txtEmail.getText());
                    DbClass.pst.setString(4, txtPassword.getText());
                    DbClass.pst.setString(5, txtURL.getText());
                    DbClass.pst.setString(6, txtDescription.getText());

                    int k = DbClass.pst.executeUpdate();
                    if (k != 0) {
                        AccountTableFetch();
                        JOptionPane.showMessageDialog(this, "Account Information Updated");
                    } else {
                        JOptionPane.showMessageDialog(this, "Account Information Not Updated", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error In Account Information Update", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error To Get Id", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateAccountActionPerformed
    String website = "";
    String name = "";
    String password = "";
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Do you want to Delete?", "DELETE", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            int row = AccountTable.getSelectedRow();
            website = AccountTable.getModel().getValueAt(row, 0).toString();
            name = AccountTable.getModel().getValueAt(row, 1).toString();
            password = AccountTable.getModel().getValueAt(row, 3).toString();
            try {
                DbClass.createCon();
                String query = "select Id from StoreAccountPassword where Registration_Id = " + userId + " and websitename = '" + website + "' and username = '" + name + "' and password = '" + password + "'";
                DbClass.pst = DbClass.con.prepareStatement(query);
                DbClass.rs = DbClass.pst.executeQuery();
                if (DbClass.rs.next()) {
                    id = DbClass.rs.getInt(1);
                    String query1 = "DELETE FROM StoreAccountPassword WHERE id = " + id;
                    DbClass.pst = DbClass.con.prepareStatement(query1);
                    DbClass.pst.executeUpdate();
                    AccountTableFetch();
                    JOptionPane.showMessageDialog(this, "Deleted Succesfully");
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Didn't Deleted", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            String websiteName = txtSearch.getText();
            Searchfetch(websiteName);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Select A Date To Search");
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        AccountTableFetch();
        txtWebsiteName.setText("");
        txtUsername.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtURL.setText("");
        txtDescription.setText("");
        txtSearch.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        SignInSignOut signInSignOut = new SignInSignOut();
        signInSignOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        new DeleteMember(userId).setVisible(true);
    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard(userId).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccountTable;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSendBugsReport;
    private javax.swing.JButton btnUpdateAccount;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWebsiteName;
    // End of variables declaration//GEN-END:variables
}
