/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storeaccountpassword;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author adittachakraborty
 */
public final class Profile extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    static int userId = 0;
    Connection con = null;
    Connection con2 = null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null;
    Statement st = null;
    Statement st2 = null;
    ResultSet rs = null;
    ResultSet rs2 = null;

    /**
     * Creates new form Profile
     *
     * @param userId
     */
    public Profile(int userId) {
        initComponents();
        JFrameIcon();
        Profile.userId = userId;
        Labelpic();
        UserInformation();
    }

    //Setting an Icon for jFrame
    void JFrameIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/password.png")));
    }

    void Labelpic() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StoreAccountPassword", "root", "Adittacse97@");
            String query = "select Picture from PROFILEPICTURE where id = " + userId;
            st = con.createStatement();
            rs = st.executeQuery(query);
            rs.next();
            try {
                InputStream inst = rs.getBinaryStream(1);
                Image im = ImageIO.read(inst);
                labelpic.setIcon(new ImageIcon(im.getScaledInstance(labelpic.getWidth(), labelpic.getHeight(), Image.SCALE_SMOOTH)));
            } catch (IOException | SQLException e) {
                ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/icons8-user_shield.png")));
                Image img1 = myImage.getImage();
                Image img2 = img1.getScaledInstance(labelpic.getWidth(), labelpic.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon i = new ImageIcon(img2);
                labelpic.setIcon(i);
                //JOptionPane.showMessageDialog(this, "Picture Or User Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error To Get User Profile Picture", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //User Information Collection
    public void UserInformation() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/StoreAccountPassword", "root", "Adittacse97@");
            String query = "Select * from Registration where Id = " + userId;
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            if (rs.next()) {
                String username = rs.getString("Username");
                txtName.setText(username);

                String email = rs.getString("Email");
                txtEmail.setText(email);

                String phoneNumber = rs.getString("PhoneNumber");
                txtPhoneNumber.setText(phoneNumber);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error To Get User", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jPhoneNumber = new javax.swing.JLabel();
        labelpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        accountPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accountPanel.setPreferredSize(new java.awt.Dimension(836, 490));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monaco", 1, 24))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 454));

        txtName.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 128, 0));
        txtName.setText("Name");

        txtEmail.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 128, 0));
        txtEmail.setText("Email");

        txtPhoneNumber.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(0, 128, 0));
        txtPhoneNumber.setText("Phone Number");

        jName.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jName.setText("Name");

        jEmail.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jEmail.setText("Email");

        jPhoneNumber.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jPhoneNumber.setText("Phone Number");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPhoneNumber)
                    .addComponent(jEmail)
                    .addComponent(jName))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber)
                    .addComponent(txtEmail)
                    .addComponent(txtName))
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jName)
                        .addGap(25, 25, 25)
                        .addComponent(jEmail)
                        .addGap(25, 25, 25)
                        .addComponent(jPhoneNumber))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addGap(25, 25, 25)
                        .addComponent(txtEmail)
                        .addGap(25, 25, 25)
                        .addComponent(txtPhoneNumber)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        labelpic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelpic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(labelpic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelpic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Profile(userId).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jName;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPhoneNumber;
    private javax.swing.JLabel labelpic;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
